export const GET_LANGUAGES = 'GET_LANGUAGES';
export const ADD_LANGUAGE = 'ADD_LANGUAGE';
export const REMOVE_LANGUAGE = 'REMOVE_LANGUAGE';
export const EDIT_LANGUAGE = 'EDIT_LANGUAGE';

export const GET_MENUITEMS = 'GET_MENUITEMS';
export const ADD_MENUITEM = 'ADD_MENUITEM';
export const REMOVE_MENUITEM = 'REMOVE_MENUITEM';
export const EDIT_MENUITEM = 'EDIT_MENUITEM';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const EDIT_NOTIFICATION = 'EDIT_NOTIFICATION';

export const GET_USERS = 'GET_USERS';
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const EDIT_USER = 'EDIT_USER';

export const GET_USERSETTINGS = 'GET_USERSETTINGS';
export const ADD_USERSETTING = 'ADD_USERSETTING';
export const REMOVE_USERSETTING = 'REMOVE_USERSETTING';
export const EDIT_USERSETTING = 'EDIT_USERSETTING';
