db.Countries.insert({"Name": "Polski", "NameEN": "Polish", "NamePL": "Polska", "ShortName":"pl", "FlagFile": "img/flag/pl.png", "Culture": "pl-PL", "Priority": 1, "IsActive": 1})
db.Countries.insert({"Name": "English", "NameEN": "English", "NamePL": "Wielka Brytania", "ShortName":"gb", "FlagFile": "img/flag/gb.png", "Culture": "en-GB", "Priority": 2, "IsActive": 1})
db.Countries.insert({"Name": "Portugues", "NameEN": "Portuguese", "NamePL": "Portugalia", "ShortName":"pt", "FlagFile": "img/flag/pt.png", "Culture": "pt-PT", "Priority": 3, "IsActive": 1})
db.Countries.insert({"Name": "Espanol", "NameEN": "Spanish", "NamePL": "Hiszpania", "ShortName":"es", "FlagFile": "img/flag/es.png", "Culture": "es-ES", "Priority": 4, "IsActive": 1})
db.Countries.insert({"Name": "Türk", "NameEN": "Turkish", "NamePL": "Turcja", "ShortName":"tr", "FlagFile": "img/flag/tr.png", "Culture": "tr-TR", "Priority": 5, "IsActive": 1})
db.Countries.insert({"Name": "Lietuvos", "NameEN": "Lithuanian", "NamePL": "Litwa", "ShortName":"lt", "FlagFile": "img/flag/lt.png", "Culture": "lt-LT", "Priority": 6, "IsActive": 1})
db.Countries.insert({"Name": "Français", "NameEN": "French", "NamePL": "Francja", "ShortName":"fr", "FlagFile": "img/flag/fr.png", "Culture": "fr-FR", "Priority": 7, "IsActive": 1})
db.Countries.insert({"Name": "Ελληνικά", "NameEN": "Greek", "NamePL": "Grecja", "ShortName":"el", "FlagFile": "img/flag/el.png", "Culture": "el-GR", "Priority": 8, "IsActive": 1})
db.Countries.insert({"Name": "Italiano", "NameEN": "Italian", "NamePL": "Włochy", "ShortName":"it", "FlagFile": "img/flag/it.png", "Culture": "it-IT", "Priority": 9, "IsActive": 1})
db.Countries.insert({"Name": "România", "NameEN": "Romanian", "NamePL": "Rumunia", "ShortName":"ro", "FlagFile": "img/flag/ro.png", "Culture": "ro-RO", "Priority": 10, "IsActive": 1})
db.Countries.insert({"Name": "Pусский", "NameEN": "Russian", "NamePL": "Rosja", "ShortName":"ru", "FlagFile": "img/flag/ru.png", "Culture": "ru-RU", "Priority": 11, "IsActive": 1})
db.Countries.insert({"Name": "Polski", "NameEN": "German", "NamePL": "Niemcy", "ShortName":"ge", "FlagFile": "img/flag/ge.png", "Culture": "de-DE", "Priority": 12, "IsActive": 1})
db.Countries.insert({"Name": "Polski", "NameEN": "Catalan", "NamePL": "Katalonia", "ShortName":"ca", "FlagFile": "img/flag/ca.png", "Culture": "ca-ES", "Priority": 13, "IsActive": 1})
db.Countries.insert({"Name": "Polski", "NameEN": "Dannish", "NamePL": "Dania", "ShortName":"da", "FlagFile": "img/flag/da.png", "Culture": "da-DK", "Priority": 14, "IsActive": 1})
db.Countries.insert({"Name": "Беларускія", "NameEN": "Belarusian", "NamePL": "Białoruś", "ShortName":"be", "FlagFile": "img/flag/be.png", "Culture": "be-BY", "Priority": 15, "IsActive": 1})
db.Countries.insert({"Name": "Deutsch (Austria)", "NameEN": "Deutsch (Austria)", "NamePL": "Polska", "ShortName":"at", "FlagFile": "img/flag/at.png", "Culture": "de-AT", "Priority": 16, "IsActive": 1})
db.Countries.insert({"Name": "Kазахский", "NameEN": "Kazakh", "NamePL": "Kazachstan", "ShortName":"kk", "FlagFile": "img/flag/kk.png", "Culture": "kk-KZ", "Priority": 17, "IsActive": 1})
db.Countries.insert({"Name": "Slovenský", "NameEN": "Slovak", "NamePL": "Słowacja", "ShortName":"sk", "FlagFile": "img/flag/sk.png", "Culture": "sk-SK", "Priority": 18, "IsActive": 1})
db.Countries.insert({"Name": "Portugues (Brasil)", "NameEN": "Portuguese (Brazil)", "NamePL": "Brazylia", "ShortName":"br", "FlagFile": "img/flag/br.png", "Culture": "pt-BR", "Priority": 19, "IsActive": 1})
db.Countries.insert({"Name": "Český", "NameEN": "Czech", "NamePL": "Czechy", "ShortName":"cz", "FlagFile": "img/flag/cz.png", "Culture": "cs-CZ", "Priority": 20, "IsActive": 1})
db.Countries.insert({"Name": "Belgium", "NameEN": "Belgium", "NamePL": "Belgia", "ShortName":"be", "FlagFile": "img/flag/be.png", "Culture": "fr-BE", "Priority": 21, "IsActive": 1})